package protocol;

public enum Commands {
    // Reservations
    CREATE_RESERVATION,
    GET_RESERVATION_HISTORY,

    // Opening Hours
    GET_OPENING_HOURS,
    UPDATE_OPENING_HOURS,

    // Tables
    GET_TABLES,
    SAVE_TABLE,
    DELETE_TABLE,

    // Users
    SUBSCRIBER_LOGIN,
    GUEST_LOGIN,
    RECOVER_SUBSCRIBER_CODE,
    RECOVER_GUEST_CONFIRMATION_CODE,
    REGISTER_SUBSCRIBER,
    UPDATE_SUBSCRIBER_DETAILS
}
